### ISSUE TITLE
addtargetmodel

### ISSUE THREAD

**Issue by Andyauk** [dojwun/doj-fishing#10]
this is the error im getting, everything is up to date.

<a href="https://ibb.co/fH1xq0t"><img src="https://i.ibb.co/x6C7X5G/fish.jpg" alt="fish" border="0"></a>

**Comment by BlueSkyNL** [comment]
> this is the error im getting, everything is up to date.
> 
> [![fish](https://camo.githubusercontent.com/ccd3781c123b3dd67286f6394abeef6b205a59acf6366f0cbf707b7ec8082693/68747470733a2f2f692e6962622e636f2f783643375835472f666973682e6a7067)](https://ibb.co/fH1xq0t)

Hello, 

You could have a look at this, if this helps you further
I have the same problem but now try this
I saw your question and thought I'll share the link with you.
if you solved the problem for yourself let me know, this is also the other way around

https://github.com/BerkieBb/qb-target/blob/main/EXAMPLES.md

**Comment by freeman4d** [comment]
you need to start qb-target before doj-fishing to fix thes error
