### ISSUE TITLE
SELLING EXOTIC FISH

### ISSUE THREAD

**Issue by elkie1991gaming** [dojwun/doj-fishing#11]
i am unable to sell the exotic fish always says that he cannot sell at the moment also hammer head shark model crashes players when caught

**Comment by AscendoTuum86** [comment]
You need the pearls card in order to sell the illegal fish.

**Comment by brynnie1** [comment]
> You need the pearls card in order to sell the illegal fish.

Where do you actually buy the pearls card from

**Comment by dojwun** [comment]
you have a random change at obtaining it from opening a fishtackle box
