### ISSUE TITLE
No Fishing Pole?

### ISSUE THREAD

**Issue by CottonMouthMax** [dojwun/doj-fishing#16]
When i get the fishing pole and try to fish, it says using fishing pole then nothing else happens. How can i fix this?

**Comment by kazz0verkill** [comment]
Having the same issue. Think it has something to do with me not using qb-inventory

**Comment by SilentGamer1980** [comment]
has anyone found out how to resolve this issue with the fishing pole not showing

**Comment by mazzillinate** [comment]
im also having this issue and getting f8 code MainThrd/ ^1SCRIPT ERROR: @doj-fishing/client/client.lua:271: No such export DrawTextUi in resource textUi^7

**Comment by graff1t13** [comment]
> im also having this issue and getting f8 code MainThrd/ ^1SCRIPT ERROR: @doj-fishing/client/client.lua:271: No such export DrawTextUi in resource textUi^7

Same here

**Comment by LtRevo12** [comment]
Hi, I have the same issue ass mentioned above. Anyone got a solution yet?

**Comment by dojwun** [comment]
should be fixed
