### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Manliketjb** [dojwun/doj-fishing#3]
no such export addtargetmodel... 

i don't know enough about qb-target to fix it

**Comment by markbucko12341** [comment]
you dont have to add nothing to your qb-target bro it all in the script

**Comment by Manliketjb** [comment]
> you dont have to add nothing to your qb-target bro it all in the script

still saying no such export addtargetmodel...

**Comment by Maureks** [comment]
same problem for me, is there anything that can be done?

**Comment by realSixGrams** [comment]
Are you all using the latest QBCore qb-target? If not, that is your issue. I simply am using the latest version, and same with the latest version of QBCore itself.

**Comment by realSixGrams** [comment]
> > you dont have to add nothing to your qb-target bro it all in the script
> 
> still saying no such export addtargetmodel...

This is simply due to your QBCore being outdated in certain areas.
