### ISSUE TITLE
I have problem with progressbar

### ISSUE THREAD

**Issue by fearofgods** [dojwun/doj-fishing#5]
I install all dependencies
![image](https://user-images.githubusercontent.com/38887416/141613277-9c113fbb-c240-4fbc-b6b5-333c9d7e02a3.png)

**Comment by markbucko12341** [comment]
your missing progressBars  
you may have progressbar  but it calling for progressBars

**Comment by markbucko12341** [comment]
iv just uploaded to my git head over there and download it bro 

https://github.com/markbucko12341/qb-progressBars-

**Comment by fearofgods** [comment]
Thank you, bro. Now it works very smoothly.
