### ISSUE TITLE
Fishing Rod stuck in hands after you are done fishing.

### ISSUE THREAD

**Issue by MerlinisaG** [dojwun/doj-fishing#7]
Any idea?

**Comment by Myles142** [comment]
you need to do /refreshskin when done

**Comment by davoucci** [comment]
i got the same issue, how can we fix that because we can warning everyone on how to fishing

**Comment by drazoxXD** [comment]
ExecuteCommand(refreshskin) maybe? I know its not a fix for it but better than nothing
