### ISSUE TITLE
AlamoSea 

### ISSUE THREAD

**Issue by balcer64** [dojwun/doj-fishing#9]
we rent a boat in different places, but we appear in AlamoSea, we rent a boat in the port of the city, the player appears in AlamoSea

**Comment by OfficerVicious** [comment]
QBCore.Functions.SpawnVehicle(Config.RentalBoat, function(boat)
					SetVehicleNumberPlateText(boat, "Rent-a-Boat")
					exports['LegacyFuel']:SetFuel(boat, 100.0)
					SetEntityHeading(boat, Config.BoatSpawnLocation.AlamoSea.w)
					TaskWarpPedIntoVehicle(PlayerPedId(), boat, -1)
					TriggerEvent("vehiclekeys:client:SetOwner", GetVehicleNumberPlateText(boat))
					SetVehicleEngineOn(boat, true, true)
				end, Config.BoatSpawnLocation.AlamoSea, true) 
			end   
			
Set this to false? It’s in the client.lua

**Comment by balcer64** [comment]
> QBCore.Functions.SpawnVehicle(Config.RentalBoat, function(boat) SetVehicleNumberPlateText(boat, "Rent-a-Boat") exports['LegacyFuel']:SetFuel(boat, 100.0) SetEntityHeading(boat, Config.BoatSpawnLocation.AlamoSea.w) TaskWarpPedIntoVehicle(PlayerPedId(), boat, -1) TriggerEvent("vehiclekeys:client:SetOwner", GetVehicleNumberPlateText(boat)) SetVehicleEngineOn(boat, true, true) end, Config.BoatSpawnLocation.AlamoSea, true) end
> 
> Set this to false? It’s in the client.lua

Config.BoatSpawnLocation.AlamoSea, false) ?

**Comment by OfficerVicious** [comment]
correct or remove the spawn location from the config

**Comment by TulaPlays** [comment]
if its the dam 
change line  300 and 352 

_elseif args == 4 then_

it was 3 but 3 already exist and that is the error.
